version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: musicplatform
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
